#!/usr/bin/ash

message() {
  echo "$@" >&2
  return 0
}

run_hook() {
  message " > Please provide the challenge."
  _skfde_response="$(fido2luks print-secret --pin)"
  message " Received Response: '$_skfde_response'"
}
