#!/bin/bash


build() {

  local mod

  add_module "dm-crypt"
  add_module "dm-integrity"
  if [[ "$CRYPTO_MODULES" ]]; then
    for mod in $CRYPTO_MODULES; do
      add_module "$mod"
    done
  else
    add_all_modules "/crypto/"
  fi

  add_binary "cryptsetup"
  add_binary "dmsetup"
  add_file "/usr/lib/udev/rules.d/10-dm.rules"
  add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
  add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
  add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"

  # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
  add_binary "/usr/lib/libgcc_s.so.1"

  add_binary "fido2luks"
  add_binary "printf"
  add_binary "sleep"
  add_file "/etc/skfde.conf" "/etc/skfde.conf"

  add_runscript
}

help() {
  cat <<HELPEOF
This allows decrypting a custom device.
HELPEOF
}
