#!/bin/bash

set -euxo pipefail

SKFDE_CONFIG_FILE="/etc/skfde.conf"
SKFDE_LUKS_KEYSLOT="3"

if [ -r "$SKFDE_CONFIG_FILE" ]; then
  . "$SKFDE_CONFIG_FILE"
else
  echo "Failed to read the SKFDE configuration file '$SKFDE_CONFIG_FILE'"
  exit 1
fi
