#!/bin/bash

set -euo pipefail

SKFDE_CONFIG_FILE="/etc/skfde.conf"
SKFDE_DEFAULT_LUKS_KEYSLOT="3"
SKFDE_LUKS_DEV=""
SKFDE_RESPONSE=""
SKFDE_PASSPHRASE=""
SKFDE_LUKS_KEYSLOT=""

while getopts ":d:s:c:h" opt; do
  case "$opt" in
    d)
      SKFDE_LUKS_DEV="$OPTARG"
      printf '%s\n' "INFO: Setting device to '$OPTARG'."
      ;;
    c)
      SKFDE_CONFIG_FILE="$OPTARG"
      printf '%s\n' "INFO: Setting config file to '$OPTARG'."
      ;;
    s)
      if [ "$OPTARG" -gt -8 ] && [ "$OPTARG" -lt 8 ]; then
        SKFDE_LUKS_KEYSLOT="$OPTARG"
        printf '%s\n' "INFO: Setting LUKS keyslot to '$OPTARG'."
      else
        printf '%s\n' "ERROR: Chosen LUKS keyslot '$OPTARG' is invalid. Please choose valid LUKS keyslot number between '0-7'."
        exit 1
      fi
      ;;
    h)
      echo
      echo " -d <device>   : select an existing device"
      echo " -s <slot>     : select the LUKS keyslot"
      echo " -c <file>     : select the skfde config file"
      exit 0
      ;;
    \?)
      printf '%s\n' "ERROR: Invalid option: '$OPTARG'" >&2
      echo
      echo " -d <device>   : select an existing device"
      echo " -s <slot>     : select the LUKS keyslot"
      echo " -c <file>     : select the skfde config file"
      exit 1
      ;;
  esac
done

if [ -r "$SKFDE_CONFIG_FILE" ]; then
  . "$SKFDE_CONFIG_FILE"
else
  echo "Failed to read the SKFDE configuration file '$SKFDE_CONFIG_FILE'"
  exit 1
fi

if [ -z "$SKFDE_LUKS_DEV" ]; then
  echo "ERROR: Device not selected. Please select an existing device using '-d' option."
  exit 1
elif [ ! -e "$SKFDE_LUKS_DEV" ]; then
  printf '%s\n' "ERROR: Selected device '$SKFDE_LUKS_DEV' doesn't exist."
  exit 1
elif [ ! -r "$SKFDE_LUKS_DEV" ] || [ ! -w "$SKFDE_LUKS_DEV" ]; then
  printf '%s\n' "ERROR: Selected device '$SKFDE_LUKS_DEV' isn't accessible for current user '$(whoami)'. Please execute this script as 'root'."
  exit 1
fi

if ! cryptsetup isLuks "$SKFDE_LUKS_DEV"; then
  printf '%s\n' "ERROR: Selected device '$SKFDE_LUKS_DEV' isn't a LUKS encrypted volume. Please select a valid device."
  exit 1
fi

if [ -z "$SKFDE_LUKS_KEYSLOT" ]; then
  SKFDE_LUKS_KEYSLOT=$SKFDE_DEFAULT_LUKS_KEYSLOT
  echo "INFO: LUKS keyslot not selected, using default LUKS keyslot."
fi

printf '%s\n' "INFO: This script will utilize LUKS keyslot '$SKFDE_LUKS_KEYSLOT' on device '$SKFDE_LUKS_DEV'."

if [ -z "$SKFDE_CHALLENGE" ]; then
  echo "ERROR: solokey challenge is empty. Check the $SKFDE_CONFIG_FILE file."
  exit 1
fi

if [ -z "$SKFDE_CREDENTIAL" ]; then
  echo "ERROR: solokey credential is empty. Check the $SKFDE_CONFIG_FILE file."
  exit 1
fi

if [ -z "$SKFDE_RESPONSE" ]; then
  read -s -p "Enter the SoloKey PIN: " PIN
  echo "Remember to press the SoloKey button if necessary"
  SKFDE_RESPONSE="$(printf $PIN | fido2luks print-secret $SKFDE_CREDENTIAL \
    --salt string:$SKFDE_CHALLENGE --pin --pin-source /dev/stdin 2>&1)"
  SKFDE_PASSPHRASE="$SKFDE_RESPONSE"
fi

echo "Please provide the LUKS passphrase for the existing keyslot"
read -s -p "Enter existing passphrase: " SKFDE_OLD_PASSPHRASE

if [ "$SKFDE_PASSPHRASE" ]; then
  printf '%s\n' " Adding solokey LUKS passphrase with cryptsetup..."
  printf '%s\n' "$SKFDE_OLD_PASSPHRASE" "$SKFDE_PASSPHRASE" "$SKFDE_PASSPHRASE" | cryptsetup --key-slot="$SKFDE_LUKS_KEYSLOT" luksAddKey "$SKFDE_LUKS_DEV" 2>&1
  _res=$?
  if [ "$_res" -eq 0 ]; then
    printf '%s\n' " New solokey passphrase successfully added"
    exit 0
  fi
else
  echo "ERROR: solokey passphrase is empty"
  exit 1
fi
