#!/bin/bash

set -euo pipefail

printf '%s\n' " Generate the SoloKey credential"

read -s -p "Enter the SoloKey PIN: " PIN
echo "Remember to press the SoloKey button if necessary"

CREDENTIAL="$(printf $PIN | fido2luks credential \
  --pin --pin-source /dev/stdin 2>&1)"

echo "SoloKey credential : $CREDENTIAL"
