#!/bin/bash

set -euo pipefail

echo "Generate the SoloKey credential"

read -s -p "Enter the SoloKey PIN and Press the button: " PIN
echo -e "\nRemember to press the SoloKey button if necessary"

CREDENTIAL="$(printf $PIN | fido2luks credential \
  --pin --pin-source /dev/stdin 2>&1)"

echo "SoloKey credential : $CREDENTIAL"
